import { Lang } from './types';

export const GRID_SIZE = 3;

export const TRANSLATIONS = {
  [Lang.EN]: {
    title: 'Slash Classic',
    playPvP: 'Play 1 vs 1',
    playPvE: 'Play vs Bot',
    rules: 'Rules',
    settings: 'Settings',
    language: 'Language',
    back: 'Back',
    menu: 'Menu',
    pause: 'Pause',
    resume: 'Resume',
    reset: 'Reset',
    forward: 'Fwd',
    winner: 'Winner',
    draw: 'Draw',
    turn: 'Turn',
    phase1: 'Phase 1: Expansion',
    phase2: 'Phase 2: Battle',
    timeout: 'Time Out!',
    rulesText: 'Phase 1: Fill board. V + H = +. \nPhase 2: + -> /. Line of 3 / wins. \nKo Rule: Cannot repeat immediate board state.',
    telegram: 'Telegram Link Copied!',
    botName: 'Bot Alpha'
  },
  [Lang.RU]: {
    title: 'Slash Classic',
    playPvP: 'Играть 1 на 1',
    playPvE: 'Играть с Ботом',
    rules: 'Правила игры',
    settings: 'Настройки',
    language: 'Язык',
    back: 'Назад',
    menu: 'Меню',
    pause: 'Пауза',
    resume: 'Продолжить',
    reset: 'Сброс',
    forward: 'Вперед',
    winner: 'Победитель',
    draw: 'Ничья',
    turn: 'Ход',
    phase1: 'Фаза 1: Заполнение',
    phase2: 'Фаза 2: Битва',
    timeout: 'Время вышло!',
    rulesText: 'Фаза 1: Заполните поле. | + — = +. \nФаза 2: + превращается в /. 3 / в ряд — победа. \nПравило Ко: Нельзя повторять предыдущий ход.',
    telegram: 'Ссылка на Telegram скопирована!',
    botName: 'Бот Альфа'
  },
  [Lang.UZ]: {
    title: 'Slash Classic',
    playPvP: '1 ga 1 o‘ynash',
    playPvE: 'Bot bilan o‘ynash',
    rules: 'O‘yin qoidalari',
    settings: 'Sozlamalar',
    language: 'Til',
    back: 'Orqaga',
    menu: 'Menyu',
    pause: 'Pauza',
    resume: 'Davom etish',
    reset: 'Qayta',
    forward: 'Oldinga',
    winner: 'G‘olib',
    draw: 'Durang',
    turn: 'Navbat',
    phase1: '1-bosqich: To‘ldirish',
    phase2: '2-bosqich: Jang',
    timeout: 'Vaqt tugadi!',
    rulesText: '1-bosqich: Kataklarni to‘ldiring. | + — = +. \n2-bosqich: + ni / ga aylantiring. 3 ta / g‘alaba. \nKo qoidasi: Oldingi yurishni qaytarish mumkin emas.',
    telegram: 'Telegram havolasi nusxalandi!',
    botName: 'Bot Alfa'
  }
};
